# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_ingestion_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'event_ingestion_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x65vent_ingestion_service.proto\x12\x11gym_framework_rpc\"^\n\nClientData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0b\n\x03\x63pf\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61ta_nascimento\x18\x04 \x01(\t\x12\x10\n\x08\x65ndereco\x18\x05 \x01(\t\"\x83\x01\n\x0fTransactionData\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\ncliente_id\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\r\n\x05valor\x18\x04 \x01(\x01\x12\r\n\x05moeda\x18\x05 \x01(\t\x12\x16\n\tcategoria\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\x0c\n\n_categoria\"v\n\tScoreData\x12\x0b\n\x03\x63pf\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\x12\x14\n\x0crenda_mensal\x18\x03 \x01(\x01\x12\x16\n\x0elimite_credito\x18\x04 \x01(\x01\x12\x1f\n\x17\x64\x61ta_ultima_atualizacao\x18\x05 \x01(\t\"G\n\x11IngestionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t2\x9e\x02\n\x15\x45ventIngestionService\x12S\n\x0cIngestClient\x12\x1d.gym_framework_rpc.ClientData\x1a$.gym_framework_rpc.IngestionResponse\x12]\n\x11IngestTransaction\x12\".gym_framework_rpc.TransactionData\x1a$.gym_framework_rpc.IngestionResponse\x12Q\n\x0bIngestScore\x12\x1c.gym_framework_rpc.ScoreData\x1a$.gym_framework_rpc.IngestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_ingestion_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTDATA']._serialized_start=52
  _globals['_CLIENTDATA']._serialized_end=146
  _globals['_TRANSACTIONDATA']._serialized_start=149
  _globals['_TRANSACTIONDATA']._serialized_end=280
  _globals['_SCOREDATA']._serialized_start=282
  _globals['_SCOREDATA']._serialized_end=400
  _globals['_INGESTIONRESPONSE']._serialized_start=402
  _globals['_INGESTIONRESPONSE']._serialized_end=473
  _globals['_EVENTINGESTIONSERVICE']._serialized_start=476
  _globals['_EVENTINGESTIONSERVICE']._serialized_end=762
# @@protoc_insertion_point(module_scope)
