# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import event_ingestion_service_pb2 as event__ingestion__service__pb2 #linha alterada para importar o arquivo corretamente

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in event_ingestion_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventIngestionServiceStub(object):
    """Serviço de ingestão de eventos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestClient = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestClient',
                request_serializer=event__ingestion__service__pb2.ClientData.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestTransaction = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestTransaction',
                request_serializer=event__ingestion__service__pb2.TransactionData.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestScore = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestScore',
                request_serializer=event__ingestion__service__pb2.ScoreData.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)


class EventIngestionServiceServicer(object):
    """Serviço de ingestão de eventos
    """

    def IngestClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTransaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestClient': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestClient,
                    request_deserializer=event__ingestion__service__pb2.ClientData.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTransaction,
                    request_deserializer=event__ingestion__service__pb2.TransactionData.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestScore': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestScore,
                    request_deserializer=event__ingestion__service__pb2.ScoreData.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gym_framework_rpc.EventIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gym_framework_rpc.EventIngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventIngestionService(object):
    """Serviço de ingestão de eventos
    """

    @staticmethod
    def IngestClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestClient',
            event__ingestion__service__pb2.ClientData.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestTransaction',
            event__ingestion__service__pb2.TransactionData.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestScore',
            event__ingestion__service__pb2.ScoreData.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
