# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import event_ingestion_service_pb2 as event__ingestion__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in event_ingestion_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventIngestionServiceStub(object):
    """Serviço de ingestão de eventos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestClients = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestClients',
                request_serializer=event__ingestion__service__pb2.IngestClientsRequest.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestTransactions = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestTransactions',
                request_serializer=event__ingestion__service__pb2.IngestTransactionsRequest.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)
        self.IngestScores = channel.unary_unary(
                '/gym_framework_rpc.EventIngestionService/IngestScores',
                request_serializer=event__ingestion__service__pb2.IngestScoresRequest.SerializeToString,
                response_deserializer=event__ingestion__service__pb2.IngestionResponse.FromString,
                _registered_method=True)


class EventIngestionServiceServicer(object):
    """Serviço de ingestão de eventos
    """

    def IngestClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestClients': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestClients,
                    request_deserializer=event__ingestion__service__pb2.IngestClientsRequest.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestTransactions': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTransactions,
                    request_deserializer=event__ingestion__service__pb2.IngestTransactionsRequest.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
            'IngestScores': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestScores,
                    request_deserializer=event__ingestion__service__pb2.IngestScoresRequest.FromString,
                    response_serializer=event__ingestion__service__pb2.IngestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gym_framework_rpc.EventIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gym_framework_rpc.EventIngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventIngestionService(object):
    """Serviço de ingestão de eventos
    """

    @staticmethod
    def IngestClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestClients',
            event__ingestion__service__pb2.IngestClientsRequest.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestTransactions',
            event__ingestion__service__pb2.IngestTransactionsRequest.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gym_framework_rpc.EventIngestionService/IngestScores',
            event__ingestion__service__pb2.IngestScoresRequest.SerializeToString,
            event__ingestion__service__pb2.IngestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
